# Generated by Django 2.0.5 on 2018-08-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
